require('dotenv').config()
module.exports = {
    APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT,
    APPWRITE_PROJECTID: process.env.APPWRITE_PROJECTID,
    APPWRITE_APIKEY: process.env.APPWRITE_APIKEY,
    APPWRITE_DATABASEID: process.env.APPWRITE_DATABASEID,
    APPWRITE_NOTE_COLLECTIONID: process.env.APPWRITE_NOTE_COLLECTIONID,
}